### ISSUE TITLE
Error running :Telescope vim_bookmarks

### ISSUE THREAD

**Issue by 0x8000-0000** [tom-anders/telescope-vim-bookmarks.nvim#3]
I'm running "Telescope vim_bookmarks" and I get the following error in the status area:

    E5108: Error executing lua ...re/nvim/plugged/telescope.nvim/lua/telescope/command.lua:100: attempt to call a nil value

I have updated all the plug-ins as of right now

    telescope.nvim : 69eb5eacff421e05aeb1e02ff97ef64bfd955c53
    telescope-vim-bookmarks.nvim : 4da66dab44f37d0de4b88cedf9e114c5b0855c20
    vim-bookmarks: 3adeae10639edcba29ea80dafa1c58cf545cb80e

**Comment by tom-anders** [comment]
Hi, you need to do either `Telescope vim_bookmarks all` or `Telescope vim_bookmarks current_file`

**Comment by 0x8000-0000** [comment]
Is there a way to set current_directory as default? "all" might be too broad, and 'current_file' too small as scopes.

**Comment by tom-anders** [comment]
Not currently. Can you please open a new issue with this feature request?
