### ISSUE TITLE
Please add a default for "Telescope vim_bookmarks"

### ISSUE THREAD

**Issue by 0x8000-0000** [tom-anders/telescope-vim-bookmarks.nvim#4]
Please add a default option to "Telescope vim_bookmarks" and make it search starting from the current directory down, recursively.

Alternatively, make the default option configurable, with the most sensible options be:
* from current directory down
* inside "this project" directory, where project is found by navigating up to the ".git", ".svn" ... - I believe there are already plug-ins for finding the project root.

I typically launch all my editor windows from the top of the tree so this would not make much of a difference to me, but maybe some users prefer to cd several layers deep.

Thank you!

**Comment by tom-anders** [comment]
For now, I changed the behavior so that `:Telescope vim_bookmarks` is equivalent to `Telescope vim_bookmarks all`.

I think the behavior you suggested of getting the bookmarks for the current directory or project root (via .git etc.) should be implemented in vim-bookmarks itself. @MattesGroeger what do you think?

**Comment by MattesGroeger** [comment]
Hey @tom-anders, thanks for all your work integrating vim-bookmarks with Telescope 🎉 👏 

I have to admit that I'm quite out of the loop regarding the plugin as I have been absent for many years 😅 . From just quickly going through my own documentation [I found this part](https://github.com/MattesGroeger/vim-bookmarks/#bookmarks-per-working-directory) which sounds like what you and @0x8000-0000 are looking for, no?

**Comment by tom-anders** [comment]
@MattesGroeger Yeah, I'd also say this looks like what we want. @0x8000-0000 If I understand this correctly, if you use this code snippet from the docu

```
" Finds the Git super-project directory.
function! g:BMWorkDirFileLocation()
    let filename = 'bookmarks'
    let location = ''
    if isdirectory('.git')
        " Current work dir is git's work tree
        let location = getcwd().'/.git'
    else
        " Look upwards (at parents) for a directory named '.git'
        let location = finddir('.git', '.;')
    endif
    if len(location) > 0
        return location.'/'.filename
    else
        return getcwd().'/.'.filename
    endif
endfunction
```
then `:Telescope vim_bookmarks` should do exactly what you want, i.e. only show you the bookmarks for the current project.

**Comment by 0x8000-0000** [comment]
@tom-anders - confirmed! It works great, thank you! (not sure why I cannot @MattesGroeger - but thank you Mattes, as well!)
